version: '2'
services:
  db:
    build: ./docker-compose-config/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: agroxydev
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - ./mysql:/var/lib/mysql
    expose:
      - "3306"
    ports:
      - 3307:3306
  php:
    build: ./docker-compose-config/php
    ports:
      - '80:80'
      - '433:433'
    expose:
      - "9000"
    volumes:
      - ./:/var/www/html
      - ./logs:/var/log/apache2
      - ./docker-compose-config/emails:/var/www/mails
    depends_on:
      - db
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    restart: always
    ports:
      - 8080:80
    volumes:
      - /sessions
    depends_on:
      - db
