version: '2'
services:


  db:
    image: 4uva4elo/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: agroxydev
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - ./mysql:/var/lib/mysql
    expose:
      - "3306"
    ports:
      - 3307:3306
    restart: always


  php:
    image: 4uva4elo/php7.0-apache
    ports:
      - '80:80'
    expose:
    # ifconfig lo0 alias 10.254.254.254 (alias for mac os lan)
      - "9000"
    volumes:
      - ./:/var/www/html
      - ./logs:/var/log/apache2
    depends_on:
      - db
      - memcached
    restart: always


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    restart: always
    ports:
      - 8080:80
    volumes:
      - /sessions
    depends_on:
      - db
    restart: always


  memcached:
    image: memcached
    ports:
      - "11211:11211"
    mem_limit: 1g
    command: memcached -m 1024m
    restart: always
