version: '3.9'
services:
  db:
    build:
      dockerfile: ./.docker/mariadb/Dockerfile
      context: .
    image: 'mariadb:latest'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: evraz
      MYSQL_USER: evraz0912
      MYSQL_PASSWORD: evraz0912
    volumes:
      - type: volume
        source: mariadb-value
        target: /var/lib/mysql:z
      - type: bind
        source: ./
        target: /var/www/html
      - type: bind
        source: /home/dev/Work/DB
        target: /db
#      - type: bind
#        source: F:\\DB
#        target: /db
    expose:
      - '3306'
    ports:
      - '3306:3306'
    networks:
      - app-network
      - network-local
  redis:
    image: redis
    restart: always
    expose:
      - '6379'
    networks:
      - app-network
  php:
    image: 4uva4elo/php7.4-fpm
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    expose:
      - '9000'
      - '9003'
      - "11300"
    volumes:
      - type: bind
        source: ./
        target: /var/www/html
      - type: bind
        source: ./logs
        target: /var/log/php
      - type: bind
        source: ./.docker/php/php.ini
        target: /usr/local/etc/php/php.ini
      - type: bind
        source: ./.docker/php/docker-php-ext-xdebug.ini
        target: /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    networks:
      - app-network
  web:
    image: 'nginx:alpine'
    ports:
      - '80:80'
    volumes:
      - type: bind
        source: ./
        target: /var/www/html
      - type: bind
        source: ./logs
        target: /var/log/nginx
      - type: bind
        source: ./.docker/nginx/site.conf
        target: /etc/nginx/conf.d/default.conf
    networks:
      - app-network
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    ports:
      - '82:80'
    volumes:
      - /sessions
    networks:
      - app-network
#  beanstalk-console:
#    image: agaveapi/beanstalkd-console
#    ports:
#      - '83:80'
#    networks:
#      - app-network
#    #  - network-local
networks:
  app-network:
    driver: bridge
  network-local: null
volumes:
  mariadb-value:
    driver: local
  beanstalkd_data: null
