FROM 	php:7.0-fpm

COPY    php.ini /usr/local/etc/php/conf.d/
COPY    sendmail.sh /usr/local/etc/php/


RUN apt-get update \
    && apt-get install -y \
        libfreetype6-dev \
        libjpeg62-turbo-dev \
        libmcrypt-dev \
        libpng12-dev \
        libz-dev libmemcached-dev libmemcached11 libmemcachedutil2 build-essential sendmail \
    && apt-get install -y --no-install-recommends unzip libssl-dev libpcre3 libpcre3-dev \
    && docker-php-ext-install pdo_mysql mysqli mbstring iconv mcrypt opcache \
    && docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ \
    && docker-php-ext-install -j$(nproc) gd
    && pecl install xdebug-2.5.0  \
    && docker-php-ext-enable xdebug \
	&& echo "xdebug.remote_enable=On" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini \
    && echo "xdebug.remote_host = 10.254.254.254" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini \
    && echo "xdebug.idekey = PHPSTORM" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini \
    && set -x \
    && chmod 777 /usr/local/etc/php/sendmail.sh && chmod +x /usr/local/etc/php/sendmail.sh \
    && cd /tmp \
    && curl -sSL -o php7.zip https://github.com/websupport-sk/pecl-memcache/archive/php7.zip \
    && unzip php7 \
    && cd pecl-memcache-php7 \
    && /usr/local/bin/phpize \
    && ./configure --with-php-config=/usr/local/bin/php-config \
    && make \
    && make install \
    && echo "extension=memcache.so" > /usr/local/etc/php/conf.d/ext-memcache.ini \
    && rm -rf /tmp/pecl-memcache-php7 php7.zip \
    && docker-php-source extract \
    && docker-php-source delete