FROM 	4uva4elo/apache-php7
RUN apt-get update && apt-get install -y \
  wget \
  unzip
  
RUN mkdir /ioncube && \
    cd /ioncube && \
    wget http://downloads3.ioncube.com/loader_downloads/ioncube_loaders_lin_x86-64.tar.gz && \
    tar xvf ioncube_loaders_lin_x86-64.tar.gz && \
    cd `php -i | grep extension_dir | cut -d' ' -f 5` && \
    cp /ioncube/ioncube/ioncube_loader_lin_7.0.so . && \
    echo zend_extension=ioncube_loader_lin_7.0.so > /usr/local/etc/php/conf.d/000-ioncube.ini && \
    rm -rf /ioncube/ \
    && docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ \
    && docker-php-ext-install -j$(nproc) gd