FROM 	php:7.0-apache

COPY 	php.ini /usr/local/etc/php/
COPY  sendmail.sh /usr/local/etc/php/

RUN  apt-get update \
    && apt-get install -y libfreetype6-dev \
           libjpeg62-turbo-dev \
           libpng12-dev \
    	     libmcrypt-dev \
           libz-dev \
           libmemcached-dev \
           libmemcached11 \
           libmemcachedutil2 \
           build-essential \
           sendmail \
           git \
           unzip \
           libssl-dev \
           libpcre3 \
           libpcre3-dev \
    && pecl install xdebug-2.5.0  \
    && docker-php-ext-enable xdebug \
    && docker-php-ext-install pdo_mysql mysqli mbstring iconv mcrypt opcache \
    && docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ \
    && docker-php-ext-install -j$(nproc) gd \
    && cp /etc/apache2/mods-available/rewrite.load /etc/apache2/mods-enabled/ \
	  && echo "xdebug.remote_enable=On xdebug.profiler_enable=0 xdebug.profiler_enable_trigger=1 xdebug.profiler_output_dir = '/var/log/apache2' xdebug.profiler_output_name = '%H%R.%s'" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini \
    && echo "xdebug.remote_host = 10.254.254.254" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini \
    && echo "xdebug.idekey = PHPSTORM" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini \
    && set -x \
    && chmod 777 /usr/local/etc/php/sendmail.sh && chmod +x /usr/local/etc/php/sendmail.sh \


    && cd /tmp \
    && git clone -b php7 https://github.com/php-memcached-dev/php-memcached memcached \
    && cd memcached \
    && /usr/local/bin/phpize \
    && ./configure --with-php-config=/usr/local/bin/php-config \
    && make \
    && make install \
    && echo "extension=memcached.so" > /usr/local/etc/php/conf.d/ext-memcached.ini \
    && rm -rf /tmp/memcached \


    && cd /tmp \
    && curl -sSL -o php7.zip https://github.com/websupport-sk/pecl-memcache/archive/php7.zip \
    && unzip php7 \
    && cd pecl-memcache-php7 \
    && /usr/local/bin/phpize \
    && ./configure --with-php-config=/usr/local/bin/php-config \
    && make \
    && make install \
    && echo "extension=memcache.so" > /usr/local/etc/php/conf.d/ext-memcache.ini \
    && rm -rf /tmp/pecl-memcache-php7 php7.zip \